### ISSUE TITLE
Bug: ETA for when the new plugin is going to be released

### ISSUE THREAD

**Issue by patpatpat123** [qltysh/codeclimate#1136]
### What happened?

You mentioned the following:

```
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
```

However, even as of now, the repo is empty.
Could you please just provide an ETA for when the repo is going to be back to normal?

This is not to rush you, it is just so we can plan our releases

### What did you expect to happen?

An ETA of when the plugin is going to be released

### Can you reproduce the problem?

Yes, consistently

### CLI Version

1

**Comment by BeardOverflow** [comment]
https://codeclimate.com/blog/code-climate-quality-is-now-qlty-software

Apologies if anyone thinks I am trolling, but is the same history again: when a new CEO arrives, the previous job is destroyed just because.

However, I agree that there should be a public plan because many users still use the product in CI/CD pipelines - and I am not talking about an ETA for the new product, but a migration plan for the legacy version too.

**Comment by brynary** [comment]
Hello! As a quick update, the new version of the CLI is now available publicly: https://github.com/qltysh/qlty
